"""empty message

Revision ID: 00c5e5ca982e
Revises: 3f72f2f3f134
Create Date: 2021-09-09 10:58:47.125411

"""

# revision identifiers, used by Alembic.
revision = '00c5e5ca982e'
down_revision = '3f72f2f3f134'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
