"""empty message

Revision ID: 07735f8d53c4
Revises: dc59703311de
Create Date: 2021-09-04 19:15:52.431099

"""

# revision identifiers, used by Alembic.
revision = '07735f8d53c4'
down_revision = 'dc59703311de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
