"""empty message

Revision ID: 08dfa212cfaa
Revises: 77b4ed25920c
Create Date: 2021-09-09 13:20:41.244077

"""

# revision identifiers, used by Alembic.
revision = '08dfa212cfaa'
down_revision = '77b4ed25920c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
