"""empty message

Revision ID: 37e7b22a44df
Revises: 5c7a32f7b221
Create Date: 2021-09-09 13:29:57.237075

"""

# revision identifiers, used by Alembic.
revision = '37e7b22a44df'
down_revision = '5c7a32f7b221'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
