"""empty message

Revision ID: 3f72f2f3f134
Revises: dd381c9af6e1
Create Date: 2021-09-06 20:02:22.252645

"""

# revision identifiers, used by Alembic.
revision = '3f72f2f3f134'
down_revision = 'dd381c9af6e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
