"""empty message

Revision ID: 540c40095297
Revises: 37e7b22a44df
Create Date: 2021-09-09 13:36:04.970906

"""

# revision identifiers, used by Alembic.
revision = '540c40095297'
down_revision = '37e7b22a44df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
