"""empty message

Revision ID: 5c7a32f7b221
Revises: 08dfa212cfaa
Create Date: 2021-09-09 13:21:22.881249

"""

# revision identifiers, used by Alembic.
revision = '5c7a32f7b221'
down_revision = '08dfa212cfaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
