"""empty message

Revision ID: 6e161b83ee55
Revises: 74e0a655249d
Create Date: 2021-09-10 20:15:04.368039

"""

# revision identifiers, used by Alembic.
revision = '6e161b83ee55'
down_revision = '74e0a655249d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
