"""empty message

Revision ID: 72ac9d0b1955
Revises: e4064da0c421
Create Date: 2021-09-09 11:08:59.704017

"""

# revision identifiers, used by Alembic.
revision = '72ac9d0b1955'
down_revision = 'e4064da0c421'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
