"""empty message

Revision ID: 73722c6c7f5f
Revises: 72ac9d0b1955
Create Date: 2021-09-09 11:11:47.277377

"""

# revision identifiers, used by Alembic.
revision = '73722c6c7f5f'
down_revision = '72ac9d0b1955'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
