"""empty message

Revision ID: 74e0a655249d
Revises: c027840653d9
Create Date: 2021-09-09 18:06:01.757827

"""

# revision identifiers, used by Alembic.
revision = '74e0a655249d'
down_revision = 'c027840653d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
