"""empty message

Revision ID: 77b4ed25920c
Revises: 99427054a4eb
Create Date: 2021-09-09 11:30:57.311419

"""

# revision identifiers, used by Alembic.
revision = '77b4ed25920c'
down_revision = '99427054a4eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
