"""empty message

Revision ID: 7dee43f1b39f
Revises: 663518bb62be
Create Date: 2021-09-04 12:12:44.776271

"""

# revision identifiers, used by Alembic.
revision = '7dee43f1b39f'
down_revision = '663518bb62be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('stevilo_kosov', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'stevilo_kosov')
    # ### end Alembic commands ###
