"""empty message

Revision ID: 8207e1510bd8
Revises: 540c40095297
Create Date: 2021-09-09 13:38:50.477086

"""

# revision identifiers, used by Alembic.
revision = '8207e1510bd8'
down_revision = '540c40095297'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
