"""empty message

Revision ID: 89a712a31801
Revises: d30175fb508b
Create Date: 2021-09-10 20:21:42.449114

"""

# revision identifiers, used by Alembic.
revision = '89a712a31801'
down_revision = 'd30175fb508b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
