"""empty message

Revision ID: 9342f1a5ea0f
Revises: c82f4d84e0e6
Create Date: 2021-09-04 19:04:33.590367

"""

# revision identifiers, used by Alembic.
revision = '9342f1a5ea0f'
down_revision = 'c82f4d84e0e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_boxes_timestamp'), 'boxes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boxes_timestamp'), table_name='boxes')
    op.drop_column('boxes', 'timestamp')
    # ### end Alembic commands ###
