"""empty message

Revision ID: 979033ee389a
Revises: b292ccd45a94
Create Date: 2021-09-04 18:43:51.159492

"""

# revision identifiers, used by Alembic.
revision = '979033ee389a'
down_revision = 'b292ccd45a94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
