"""empty message

Revision ID: 99427054a4eb
Revises: bed8644e13aa
Create Date: 2021-09-09 11:26:34.646351

"""

# revision identifiers, used by Alembic.
revision = '99427054a4eb'
down_revision = 'bed8644e13aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
