"""empty message

Revision ID: a89dee687480
Revises: 979033ee389a
Create Date: 2021-09-04 18:57:48.990845

"""

# revision identifiers, used by Alembic.
revision = 'a89dee687480'
down_revision = '979033ee389a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
