"""slike

Revision ID: bb03e5ac95a5
Revises: 8a6d8c898942
Create Date: 2021-09-12 18:34:53.525566

"""

# revision identifiers, used by Alembic.
revision = 'bb03e5ac95a5'
down_revision = '8a6d8c898942'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
