"""empty message

Revision ID: bed8644e13aa
Revises: 73722c6c7f5f
Create Date: 2021-09-09 11:22:04.448890

"""

# revision identifiers, used by Alembic.
revision = 'bed8644e13aa'
down_revision = '73722c6c7f5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
