"""empty message

Revision ID: c027840653d9
Revises: 8207e1510bd8
Create Date: 2021-09-09 15:43:15.097173

"""

# revision identifiers, used by Alembic.
revision = 'c027840653d9'
down_revision = '8207e1510bd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
