"""empty message

Revision ID: c82f4d84e0e6
Revises: a89dee687480
Create Date: 2021-09-04 18:59:09.736855

"""

# revision identifiers, used by Alembic.
revision = 'c82f4d84e0e6'
down_revision = 'a89dee687480'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
