"""empty message

Revision ID: d30175fb508b
Revises: 6e161b83ee55
Create Date: 2021-09-10 20:20:30.663870

"""

# revision identifiers, used by Alembic.
revision = 'd30175fb508b'
down_revision = '6e161b83ee55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
