"""empty message

Revision ID: dc59703311de
Revises: 9342f1a5ea0f
Create Date: 2021-09-04 19:10:25.092418

"""

# revision identifiers, used by Alembic.
revision = 'dc59703311de'
down_revision = '9342f1a5ea0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
