"""empty message

Revision ID: dd381c9af6e1
Revises: 267310e21971
Create Date: 2021-09-04 22:34:22.284479

"""

# revision identifiers, used by Alembic.
revision = 'dd381c9af6e1'
down_revision = '267310e21971'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
