"""empty message

Revision ID: e4064da0c421
Revises: 00c5e5ca982e
Create Date: 2021-09-09 10:59:36.124272

"""

# revision identifiers, used by Alembic.
revision = 'e4064da0c421'
down_revision = '00c5e5ca982e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('spremenjeno', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_boxes_spremenjeno'), 'boxes', ['spremenjeno'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boxes_spremenjeno'), table_name='boxes')
    op.drop_column('boxes', 'spremenjeno')
    # ### end Alembic commands ###
